default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: asdasd123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: green_development
  host: localhost
  # port: 5432

test:
  <<: *default
  database: green_test
  host: localhost
  
production:
  <<: *default
  # username: deploy
  # password: root123
  database: green_production