check_offer_expiry_worker:
  cron: "0 7 * * *" # Everyday at 7:00 AM
  # cron: "* * * * *" # Every minute
  queue: default
  class: "CheckOfferExpiryWorker"


notification_expiry_worker:
  cron: "*/10 * * * *" # Every 10 minutes
  # cron: "* * * * *" # Every minute
  queue: default
  class: "NotificationExpiryWorker"