check_offer_expiry_worker:
  # cron: "59 * * * *" # Every 1 hour
  # cron: "*/5 * * * *" # Every 5 minutes
  cron: "* * * * *" # Every minute
  queue: default
  class: "CheckOfferExpiryWorker"


notification_expiry_worker:
  # cron: "59 * * * *" # Every 1 hour
  # cron: "*/5 * * * *" # Every 5 minutes
  cron: "* * * * *" # Every minute
  queue: default
  class: "NotificationExpiryWorker"